# Satz von Bayes und Hidden Markov Models
## 1. Satz von Bayes

Bob möchte gerne wissen, ob es regnet. Dazu schaut er aus dem Fenster, ob die Straße nass ist. Wenn es tatsächlich regnet, ist die Straße mit einer Wahrscheinlichkeit von 95 % nass (in 5 % der Fälle regnet es noch nicht lange genug, damit die Straße für Bob nass aussieht). Wenn es nicht regnet, ist die Straße mit einer Wahrscheinlichkeit von 25 % nass (weil der Nachbar von Bob den Rasensprenger laufen lässt, der auch die Straße trifft). Darüber hinaus weiß Bob, dass es an 40 % aller Tage regnet. Benutzen Sie für die folgenden Aufgaben die folgende Notation:

* $r$: Es regnet.
* $\bar{r}$: Es regnet nicht.
* $n$: Die Straße ist nass.

Berechnen Sie die folgenden Wahrscheinlichkeiten:
* $p(r) = $
* $p(\bar{r}) = $
* $p(n|r) = $
* $p(n|\bar{r}) = $
* $p(r|n) = $

## 2. Hidden-Markov-Modelle
Für eine Smartwatch soll ein System entwickelt werden, das automatisch erkennt, ob der
Träger gerade schläft. Die Smartwatch enthält einen Beschleunigungssensor, der entwe-
der den Wert wenig Bewegung“ oder den Wert viel Bewegung“ zurückliefert. Wenn der
Träger schläft, ist die Wahrscheinlichkeit für viel Bewegung“ 5 % und die Wahrscheinlichkeit für wenig Bewegung“ 95 %. Wenn der Träger wach ist, ist die Wahrscheinlichkeit
für viel Bewegung“ 60 % und die Wahrscheinlichkeit für wenig Bewegung“ 40 %. Wenn
der Träger schläft, ist die Wahrscheinlichkeit, dass er im nächsten Zeitschritt wach ist,
30 %. Wenn der Träger wach ist, ist die Wahrscheinlichkeit, dass er im nächsten Schritt
schläft, 20 %. Zu Anfang schläft der Träger mit einer Wahrscheinlichkeit von 50 %.

1. Spezifizieren Sie diesen Prozess als HMM, wobei der Zustand beschreibt, ob die Person schläft oder wach ist. Notieren Sie die Initialzustand und das Beobachtungsmodell.   

2. Berechnen Sie, ausgehend von der initialen Wahrscheinlichkeitsverteilung über den Zuständen, ...   
   a) die Vorhersage, d.h., Wahrscheinlichkeitsverteilung allein auf Basis des Transitionsmodelles!   

   b) die Korrektur nach der Beobachtung wenig Bewegung“!   


## 2. Implementierung

### Aufgabe 1 
Implementieren Sie zunächst für das oben beschriebene HMM das die Modelle für Transition und Observation, wie den Initalzustand des Systems! 

In [1]:
import numpy as np

In [2]:
#transition model
T = "Implement me!"
#prior
s0 = "Implement me!"

#obs model
O = "Implement me!"

### Aufgabe 2
Implementieren Sie eine Funktion `predict(s,T)` die als Parameter eine Prior-Verteilung $p(x_t | y_{1:t})$ als Vektor $s$ und das Transitionsmodell als Matrix `A` bekommt und als Ausgabe die Verteilung $p(x_{t+1} | y_{1:t})$ liefert.

In [3]:
def predict(s, T):
    return "Implement me!"

### Aufgabe 3
Implementieren Sie eine Funktion `update(s,O,y)` die als Parameter eine Verteilung $p(x_{t+1} | y_{1:t})$ als Vektor $s$, ein Observationsmodell als Matrix `O` und eine Beobachtung $y_{t+1}$ als Integer `y` bekommt und als Ausgabe $p(x_{t+1} | y_{1:t+1})$ liefert.

In [4]:
def update(s, O, y):
    return "Implement me!"

### Aufgabe 4
Implementieren Sie eine Funktion `filter(s0,Y,T,O)` die als Parameter eine Prior-Verteilung $p(x_0)$ als Vektor `s0`, ein Transitions- und Beobachtungsmodell als Matrizen `T` und `O` und eine Sequenz von Beobachtungen $y_{1:T}$ als Vektor `yy` bekommt und für jedes $t = 1,...,T$ die Verteilung $p(x_t | y_{1:t})$ als Vektor berechnet und als Aufgabe somit eine $T \times 2$-Matrix liefert.

In [5]:
def filter(s0, O, T, yy):
    return "Implement me!"

Testen Sie nun ihre Implementierung mit dem untenstehenden Code.

In [6]:
yy = ["W","W","V"]
ss = filter(s0,O,T,yy)
ss

[array([[0.5],
        [0.5]]),
 array([[0.33976834],
        [0.66023166]]),
 array([[0.2717807],
        [0.7282193]]),
 array([[0.90265233],
        [0.09734767]])]